name: SeeKillFild
version: '1.1.0'
main: su.seemine.seekillfild.SeeKillFild
api-version: '1.16'
authors: [GDev]
description: "Плагин на вывод Title, SubTitle, ActionBar, BossBar и Message при убийстве."
website: https://seemine.su
commands:
  skf:
    description: "Перезагрузить конфигурацию плагина"
    usage: "/skf"
    permission: seekillfild.reload
    aliases: [seekillfild]

permissions:
  seekillfild.reload:
    description: "Позволяет перезагружать конфигурацию плагина"
    default: op